-- Schema for master_specs_db
-- Generated on 2025-10-11T11:17:54.404Z

-- Table: serialized_inventory
CREATE TABLE `serialized_inventory` ( `serial_id` int(11) NOT NULL AUTO_INCREMENT, `product_id` bigint(20) unsigned NOT NULL, `serial_number` varchar(255) NOT NULL, `warehouse_id` int(11) DEFAULT NULL, `zone_id` int(11) DEFAULT NULL, `status` enum('available','reserved','sold','damaged','returned') DEFAULT 'available', `created_at` datetime DEFAULT current_timestamp(), `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(), PRIMARY KEY (`serial_id`), UNIQUE KEY `serial_number` (`serial_number`), KEY `fk_serial_to_specs` (`product_id`), KEY `fk_serial_to_warehouse` (`warehouse_id`), KEY `fk_serial_to_zone` (`zone_id`), KEY `idx_status_warehouse` (`status`,`warehouse_id`), CONSTRAINT `fk_serial_to_specs` FOREIGN KEY (`product_id`) REFERENCES `specs_db` (`product_id`) ON DELETE CASCADE, CONSTRAINT `fk_serial_to_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`warehouse_id`) ON DELETE SET NULL, CONSTRAINT `fk_serial_to_zone` FOREIGN KEY (`zone_id`) REFERENCES `warehouse_zones` (`zone_id`) ON DELETE SET NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

-- View: warehouse_distribution_overview
CREATE VIEW `warehouse_distribution_overview` AS select `w`.`warehouse_id` AS `warehouse_id`,`w`.`name` AS `warehouse_name`,count(distinct `wz`.`zone_id`) AS `total_zones`,coalesce(`bulk_inventory`.`total_quantity`,0) + coalesce(`serialized_inventory`.`total_quantity`,0) AS `total_inventory` from (((`warehouses` `w` left join `warehouse_zones` `wz` on(`w`.`warehouse_id` = `wz`.`warehouse_id` and `wz`.`is_active` = 1)) left join (select `warehouse_product_locations`.`warehouse_id` AS `warehouse_id`,sum(`warehouse_product_locations`.`quantity`) AS `total_quantity` from `warehouse_product_locations` group by `warehouse_product_locations`.`warehouse_id`) `bulk_inventory` on(`w`.`warehouse_id` = `bulk_inventory`.`warehouse_id`)) left join (select `serialized_inventory`.`warehouse_id` AS `warehouse_id`,count(`serialized_inventory`.`serial_id`) AS `total_quantity` from `serialized_inventory` where `serialized_inventory`.`status` in ('available','reserved') group by `serialized_inventory`.`warehouse_id`) `serialized_inventory` on(`w`.`warehouse_id` = `serialized_inventory`.`warehouse_id`)) where `w`.`is_active` = 1 group by `w`.`warehouse_id`

-- Table: warehouses
CREATE TABLE `warehouses` ( `warehouse_id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `location` text DEFAULT NULL, `description` text DEFAULT NULL, `contact_info` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`contact_info`)), `is_active` tinyint(1) DEFAULT 1, `created_at` datetime DEFAULT current_timestamp(), `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(), PRIMARY KEY (`warehouse_id`), KEY `idx_warehouse_name` (`name`), KEY `idx_warehouse_active` (`is_active`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

-- Table: specs_db
CREATE TABLE `specs_db` ( `product_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `device_name` varchar(255) DEFAULT NULL, `device_maker` varchar(255) DEFAULT NULL, `device_price` decimal(10,2) DEFAULT NULL, `color` varchar(50) DEFAULT NULL, `water_and_dust_rating` varchar(50) DEFAULT NULL, `processor` varchar(255) DEFAULT NULL, `process_node` varchar(50) DEFAULT NULL, `cpu_cores` varchar(50) DEFAULT NULL, `cpu_frequency` varchar(100) DEFAULT NULL, `gpu` varchar(100) DEFAULT NULL, `memory_type` varchar(50) DEFAULT NULL, `ram` varchar(50) DEFAULT NULL, `rom` varchar(50) DEFAULT NULL, `expandable_memory` varchar(100) DEFAULT NULL, `length_mm` decimal(5,2) DEFAULT NULL, `width_mm` decimal(5,2) DEFAULT NULL, `thickness_mm` decimal(4,2) DEFAULT NULL, `weight_g` decimal(5,2) DEFAULT NULL, `display_size` decimal(4,2) DEFAULT NULL, `resolution` varchar(50) DEFAULT NULL, `pixel_density` varchar(50) DEFAULT NULL, `refresh_rate` varchar(50) DEFAULT NULL, `brightness` varchar(100) DEFAULT NULL, `display_features` text DEFAULT NULL, `rear_camera_main` varchar(255) DEFAULT NULL, `rear_camera_macro` varchar(255) DEFAULT NULL, `rear_camera_features` text DEFAULT NULL, `rear_video_resolution` varchar(255) DEFAULT NULL, `front_camera` varchar(255) DEFAULT NULL, `front_camera_features` text DEFAULT NULL, `front_video_resolution` varchar(255) DEFAULT NULL, `battery_capacity` varchar(50) DEFAULT NULL, `fast_charging` varchar(100) DEFAULT NULL, `connector` varchar(50) DEFAULT NULL, `security_features` text DEFAULT NULL, `sim_card` varchar(100) DEFAULT NULL, `nfc` varchar(50) DEFAULT NULL, `network_bands` text DEFAULT NULL, `wireless_connectivity` text DEFAULT NULL, `navigation` text DEFAULT NULL, `audio_jack` varchar(50) DEFAULT NULL, `audio_playback` text DEFAULT NULL, `video_playback` text DEFAULT NULL, `sensors` text DEFAULT NULL, `operating_system` varchar(100) DEFAULT NULL, `package_contents` text DEFAULT NULL, `device_inventory` int(11) DEFAULT NULL, `product_type` varchar(255) DEFAULT NULL, PRIMARY KEY (`product_id`) ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

-- Table: security_events
CREATE TABLE `security_events` ( `id` int(11) NOT NULL AUTO_INCREMENT, `event_type` enum('login_success','logout','failed_login','password_change','account_lockout','token_invalidation') NOT NULL, `user_id` int(11) DEFAULT NULL, `ip_address` varchar(45) DEFAULT NULL, `user_agent` text DEFAULT NULL, `session_id` varchar(32) DEFAULT NULL, `details` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`details`)), `risk_level` enum('low','medium','high','critical') DEFAULT 'low', `created_at` timestamp NULL DEFAULT current_timestamp(), PRIMARY KEY (`id`), KEY `idx_event_type` (`event_type`), KEY `idx_user_id` (`user_id`), KEY `idx_created_at` (`created_at`), KEY `idx_ip_address` (`ip_address`), CONSTRAINT `fk_event_to_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ) ENGINE=InnoDB AUTO_INCREMENT=72 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

-- Table: warehouse_product_locations
CREATE TABLE `warehouse_product_locations` ( `location_id` int(11) NOT NULL AUTO_INCREMENT, `warehouse_id` int(11) NOT NULL, `zone_id` int(11) DEFAULT NULL, `product_id` bigint(20) unsigned NOT NULL, `quantity` int(11) DEFAULT 0, `reserved_quantity` int(11) DEFAULT 0, `min_stock_level` int(11) DEFAULT 0, `created_at` datetime DEFAULT current_timestamp(), `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(), PRIMARY KEY (`location_id`), UNIQUE KEY `unique_warehouse_zone_phone` (`warehouse_id`,`zone_id`,`product_id`), KEY `fk_wpl_to_zone` (`zone_id`), KEY `fk_wpl_to_specs` (`product_id`), CONSTRAINT `fk_wpl_to_specs` FOREIGN KEY (`product_id`) REFERENCES `specs_db` (`product_id`) ON DELETE CASCADE, CONSTRAINT `fk_wpl_to_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`warehouse_id`) ON DELETE CASCADE, CONSTRAINT `fk_wpl_to_zone` FOREIGN KEY (`zone_id`) REFERENCES `warehouse_zones` (`zone_id`) ON DELETE SET NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

-- Table: warehouse_zones
CREATE TABLE `warehouse_zones` ( `zone_id` int(11) NOT NULL AUTO_INCREMENT, `warehouse_id` int(11) NOT NULL, `name` varchar(255) NOT NULL, `description` text DEFAULT NULL, `zone_type` enum('receiving','storage','picking','staging','shipping') DEFAULT 'storage', `capacity_limit` int(11) DEFAULT NULL, `is_active` tinyint(1) DEFAULT 1, `created_at` datetime DEFAULT current_timestamp(), `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(), PRIMARY KEY (`zone_id`), KEY `idx_zone_warehouse` (`warehouse_id`), CONSTRAINT `fk_zone_to_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`warehouse_id`) ON DELETE CASCADE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

-- Table: receipts
CREATE TABLE `receipts` ( `receipt_id` varchar(50) NOT NULL, `receipt_type` enum('incoming','outgoing') NOT NULL, `receipt_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`receipt_data`)), `supplier_id` int(11) DEFAULT NULL, `transaction_date` datetime DEFAULT current_timestamp(), `subtotal` decimal(10,2) DEFAULT 0.00, `tax_amount` decimal(10,2) DEFAULT 0.00, `total_amount` decimal(10,2) DEFAULT 0.00, `notes` text DEFAULT NULL, `created_at` datetime DEFAULT current_timestamp(), `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(), PRIMARY KEY (`receipt_id`), KEY `idx_supplier_id` (`supplier_id`), KEY `idx_transaction_date` (`transaction_date`), KEY `idx_receipt_type` (`receipt_type`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

-- Table: invalidated_tokens
CREATE TABLE `invalidated_tokens` ( `id` int(11) NOT NULL AUTO_INCREMENT, `token_hash` varchar(64) NOT NULL, `token_type` enum('session','remember','reset','api') NOT NULL DEFAULT 'session', `user_id` int(11) DEFAULT NULL, `expires_at` timestamp NOT NULL, `reason` varchar(100) DEFAULT 'logout', `invalidated_at` timestamp NULL DEFAULT current_timestamp(), PRIMARY KEY (`id`), UNIQUE KEY `token_hash` (`token_hash`), KEY `idx_expires_at` (`expires_at`), KEY `idx_user_id` (`user_id`), CONSTRAINT `fk_token_to_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

-- Table: inventory_log
CREATE TABLE `inventory_log` ( `log_id` int(11) NOT NULL AUTO_INCREMENT, `product_id` bigint(20) unsigned NOT NULL, `transaction_type` enum('incoming','outgoing','adjustment','transfer') NOT NULL, `quantity_changed` int(11) NOT NULL, `transaction_date` datetime DEFAULT current_timestamp(), `warehouse_id` int(11) DEFAULT NULL, `zone_id` int(11) DEFAULT NULL, `serial_id` int(11) DEFAULT NULL, `batch_id` int(11) DEFAULT NULL, `receipt_id` varchar(50) DEFAULT NULL, `user_id` int(11) DEFAULT NULL, `notes` text DEFAULT NULL, `created_at` datetime DEFAULT current_timestamp(), `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(), PRIMARY KEY (`log_id`), KEY `fk_log_to_specs` (`product_id`), KEY `fk_log_to_warehouse` (`warehouse_id`), KEY `fk_log_to_zone` (`zone_id`), KEY `fk_log_to_serial` (`serial_id`), KEY `fk_log_to_batch` (`batch_id`), KEY `fk_log_to_receipt` (`receipt_id`), CONSTRAINT `fk_log_to_batch` FOREIGN KEY (`batch_id`) REFERENCES `batch_tracking` (`batch_id`) ON DELETE SET NULL, CONSTRAINT `fk_log_to_receipt` FOREIGN KEY (`receipt_id`) REFERENCES `receipts` (`receipt_id`) ON DELETE SET NULL, CONSTRAINT `fk_log_to_serial` FOREIGN KEY (`serial_id`) REFERENCES `serialized_inventory` (`serial_id`) ON DELETE SET NULL, CONSTRAINT `fk_log_to_specs` FOREIGN KEY (`product_id`) REFERENCES `specs_db` (`product_id`) ON DELETE CASCADE, CONSTRAINT `fk_log_to_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`warehouse_id`) ON DELETE SET NULL, CONSTRAINT `fk_log_to_zone` FOREIGN KEY (`zone_id`) REFERENCES `warehouse_zones` (`zone_id`) ON DELETE SET NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

-- Table: batch_tracking
CREATE TABLE `batch_tracking` ( `batch_id` int(11) NOT NULL AUTO_INCREMENT, `product_id` bigint(20) unsigned NOT NULL, `warehouse_id` int(11) DEFAULT NULL, `zone_id` int(11) DEFAULT NULL, `batch_no` varchar(100) NOT NULL, `quantity` int(11) NOT NULL DEFAULT 0, `created_at` datetime DEFAULT current_timestamp(), `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(), PRIMARY KEY (`batch_id`), UNIQUE KEY `unique_batch_product_location` (`batch_no`,`product_id`,`warehouse_id`,`zone_id`), KEY `fk_batch_to_specs` (`product_id`), KEY `fk_batch_to_warehouse` (`warehouse_id`), KEY `fk_batch_to_zone` (`zone_id`), CONSTRAINT `fk_batch_to_specs` FOREIGN KEY (`product_id`) REFERENCES `specs_db` (`product_id`) ON DELETE CASCADE, CONSTRAINT `fk_batch_to_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`warehouse_id`) ON DELETE SET NULL, CONSTRAINT `fk_batch_to_zone` FOREIGN KEY (`zone_id`) REFERENCES `warehouse_zones` (`zone_id`) ON DELETE SET NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

-- Table: suppliers
CREATE TABLE `suppliers` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `category` varchar(100) DEFAULT NULL, `contact_person` varchar(255) DEFAULT NULL, `contact_position` varchar(100) DEFAULT NULL, `contact_email` varchar(255) DEFAULT NULL, `email` varchar(255) DEFAULT NULL, `phone` varchar(50) DEFAULT NULL, `website` varchar(255) DEFAULT NULL, `address` text DEFAULT NULL, `notes` text DEFAULT NULL, `is_active` tinyint(1) DEFAULT 1, `created_at` timestamp NULL DEFAULT current_timestamp(), `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(), PRIMARY KEY (`id`), KEY `idx_supplier_name` (`name`), KEY `idx_supplier_category` (`category`), KEY `idx_contact_person` (`contact_person`), KEY `idx_contact_email` (`contact_email`), KEY `idx_email` (`email`), KEY `idx_is_active` (`is_active`) ) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

-- Table: users
CREATE TABLE `users` ( `id` int(11) NOT NULL AUTO_INCREMENT, `username` varchar(50) NOT NULL, `password` varchar(255) NOT NULL, `full_name` varchar(100) NOT NULL, `email` varchar(255) NOT NULL, `role` enum('staff','admin') NOT NULL DEFAULT 'staff', `is_active` tinyint(1) DEFAULT 1, `last_login` timestamp NULL DEFAULT NULL, `failed_login_attempts` int(11) DEFAULT 0, `locked_until` timestamp NULL DEFAULT NULL, `created_at` timestamp NULL DEFAULT current_timestamp(), `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(), PRIMARY KEY (`id`), UNIQUE KEY `username` (`username`), UNIQUE KEY `email` (`email`), KEY `idx_role` (`role`), KEY `idx_is_active` (`is_active`) ) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

-- Table: user_token_validity
CREATE TABLE `user_token_validity` ( `user_id` int(11) NOT NULL, `validate_tokens_after` timestamp NOT NULL, `reason` varchar(100) DEFAULT 'security_action', `created_at` timestamp NULL DEFAULT current_timestamp(), `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(), PRIMARY KEY (`user_id`), CONSTRAINT `fk_validity_to_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

